#!/usr/bin/sh
echo 'ready to install HIS frontend ...'
echo '[1] installing dotenv config parser...'
yarn install
echo '[2] installing file server dependencies...'
cd fileserver && yarn install && cd ..
echo '[3] installing frontend dependencies...'
cd frontend && yarn install && cd ..
echo '[4] installing middleware dependencies...'
cd middleware && yarn install && cd ..
echo 'OK!'

echo 'generating config...'
node configure
echo 'ready to run middleware...'
cd middleware && node index.js&
echo 'started.'
echo 'ready to run fileserver...'
cd fileserver && node index.js&
echo 'started.'
echo 'ready to run webpack dev server...'
cd frontend && yarn start
echo 'started.'