
version: '3'
services:
  db:
    image: mariadb
  frontend:
    container_name: his-frontend-nginx
    restart: always
    build: ./frontend
    volumes:
      - .:/home/his
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "80:80"
  
