#!/usr/bin/sh
echo 'ready to install HIS frontend ...'
echo '[1] installing dotenv config parser...'
yarn install
echo '[2] installing middleware dependencies...'
cd frontend && yarn install
echo '[3] installing middleware dependencies...'
cd frontend && yarn install
echo 'OK!'